### ISSUE TITLE
Remove geocode control box from routing instructions

### ISSUE THREAD

**Issue by amyleew** [amyleew/osrm-frontend#14]
@tristen - Having trouble identifying where my `control box` is connected to the `routing instructions` but they are clearly connected. 

How can I best trouble-shoot this?

![image](https://cloud.githubusercontent.com/assets/4587826/8659958/2f991d2e-297c-11e5-9462-a480a3d6e110.png)

**Comment by amyleew** [comment]
On this [http://amyleew.github.io/osrm-frontend/](http://amyleew.github.io/osrm-frontend/) I'm trying to get the `control box` separate from the `routing instructions` like on my [http://amyleew.github.io/lrm/](http://amyleew.github.io/lrm/) version within the `npm install`.

![image](https://cloud.githubusercontent.com/assets/4587826/8660910/fe0a287e-2981-11e5-9caa-1ff1b6b30998.png)

**Comment by tristen** [comment]
Discussed offline with @amyleew. It looks like the parent container (right sidebar) has it's container set `overflow:auto` which prevented the fixed positioned geocoding container from appearing.

Ideally, the geocoding container is never contained within that sidebar and appended to the map element independently. Looking at http://www.liedman.net/leaflet-routing-machine/api/ it doesn't look like its really possible to do.

**Comment by tristen** [comment]
https://github.com/perliedman/leaflet-routing-machine/issues/135

**Comment by amyleew** [comment]
@tristen - I was able to successfully sever the geocoder input for the direction instructions... [leaflet-routing-alternatives-container and .osrm-directions-inputs had the same styling](https://github.com/amyleew/osrm-frontend/commit/0d4f2fff8baa831d19e9457dd2893c7fc984d3b9) 

However now I can't control the `overflow: auto` so I can scroll longer routing instructions. Try to replace in the parent container and the direction instructions classes but no luck. Am I missing something?

![image](https://cloud.githubusercontent.com/assets/4587826/8712392/c11e2cd6-2b29-11e5-9522-e5c92b522f5b.png)

**Comment by tristen** [comment]
You'll want to give its parent container overflow of auto and a height of 100%. Make sure there isn't any weird positioning rules applied to it.

**Comment by amyleew** [comment]
Yes!! `height: 100%;` thanks!  Fixed https://github.com/amyleew/osrm-frontend/commit/b5b9936a731992f5a6d2d1ab2b23f595f3507ad2
