### ISSUE TITLE
Add entire toolbar 

### ISSUE THREAD

**Issue by amyleew** [amyleew/osrm-frontend#16]
@TheMatrex - Looks like entire toolbar is being placed with classes and functionality added in [/src/tools.js](https://github.com/Project-OSRM/osrm-frontend-v2/blob/master/src/tools.js). 

![image](https://cloud.githubusercontent.com/assets/4587826/8713731/58c6472a-2b3a-11e5-9b4c-fa53086cd010.png)

I tried to roll this into my code, the main error I'm stuck on is reading link button code in DOM event. 

```
linkButton.title = localization[this.options.language]['Link']
```

![image](https://cloud.githubusercontent.com/assets/4587826/8714287/1d2d545e-2b41-11e5-9bdc-1c7c88e7aa84.png)

I also got an error with `npm run build`:

```
WARN: Side effects in initialization of unused variable viewOptions [-:37,4]
```

What am I doing wrong here? Recent push https://github.com/amyleew/osrm-frontend/commit/417b70158bd7329ae2946a13c46c371781cd1743

/cc @tristen

**Comment by tristen** [comment]
Does `this.options.language` return `en` or `de`? Also, I'd write `['link']` in [dot notation](https://github.com/airbnb/javascript#properties) instead.

**Comment by amyleew** [comment]
Thanks @tristen. Success!

![image](https://cloud.githubusercontent.com/assets/4587826/8726584/1fc30fb6-2ba9-11e5-821d-4861412cde3c.png)

`this.options.language` was `undefined`, because it was not referenced in `lrm_options.js`. Added `require('./leaflet_options');` and referenced in `tools` object [src/lrm_options.js#L41](https://github.com/amyleew/osrm-frontend/blob/c5b461ee2bcf62e5cff8436188fbb99203534484/src/lrm_options.js#L41)
