### ISSUE TITLE
Deployed version doesn't work

### ISSUE THREAD

**Issue by freenerd** [amyleew/osrm-frontend#25]
Going to https://amyleew.github.io/osrm-frontend/ won't work for me, even after doing `window.localStorage.setItem('mapbox_access_token', 'YOUR TOKEN')` i get scrambled tiles.

![screen shot 2015-07-27 at 11 47 23](https://cloud.githubusercontent.com/assets/25713/8903019/41471f60-3455-11e5-802e-de885811448c.png)

/cc @amyleew

**Comment by amyleew** [comment]
@freenerd - Works properly over [**http**://amyleew.github.io/osrm-frontend/](http://amyleew.github.io/osrm-frontend/) not **https**. 
Can you try that url?

Same as [http://map.project-osrm.org/](http://map.project-osrm.org/) and [http://project-osrm.org/osrm-frontend-v2/](http://project-osrm.org/osrm-frontend-v2/). 
Does this need to be https??

**Comment by freenerd** [comment]
@amyleew it would be great if both would work with https (this prevents some attacks on our users). For this to work, all external resources need to be loaded via https as well. Could you change the leaflet files from http to https?

They are here:
- https://github.com/amyleew/osrm-frontend/blob/1dce334bab1f523567ebbb6ae8664da717389393/map.html#L7-L8
- https://github.com/amyleew/osrm-frontend/blob/1dce334bab1f523567ebbb6ae8664da717389393/index.html#L7-L8

Also, why is there map.html and index.html? They look redundant.

**Comment by amyleew** [comment]
@freenerd Updated `https` change, should be working fine. Also deleted `map.html`
