### ISSUE TITLE
Viewport seems bigger than 100%

### ISSUE THREAD

**Issue by amyleew** [amyleew/osrm-frontend#26]
The `viewport` is never quite 100%. A scroll always shows up but the `vh` combine to `100`. 

![image](https://cloud.githubusercontent.com/assets/4587826/9125336/cda61248-3c6d-11e5-8a20-8153ad27d11d.png)

_footer never makes it..._
![image](https://cloud.githubusercontent.com/assets/4587826/9125344/e2b3f1f0-3c6d-11e5-8d22-16a08b320932.png)

What am I missing @tristen?

**Comment by tristen** [comment]
You are applying a fixed height in places with that `min-height` rule:

<img width="830" alt="screen shot 2015-08-07 at 9 31 09 am" src="https://cloud.githubusercontent.com/assets/61150/9136761/1e5cec7e-3ce7-11e5-93bf-e46a07ff0188.png">

**Comment by amyleew** [comment]
fixed
