### ISSUE TITLE
Add small components layer

### ISSUE THREAD

**Issue by freenerd** [amyleew/osrm-frontend#28]
Currently map.project-osrm.org has a layer for "small components" and I think the re-design doesn't include that one yet? It should though, @amyleew possible to add?

<img width="152" alt="screen shot 2015-08-19 at 12 45 02" src="https://cloud.githubusercontent.com/assets/25713/9354371/26a10388-4670-11e5-8b26-6664505b847a.png">

**Comment by amyleew** [comment]
Thanks! Added to the list @freenerd https://github.com/Project-OSRM/osrm-frontend-v2/issues/72
