### ISSUE TITLE
Add open / edit in JOSM button

### ISSUE THREAD

**Issue by amyleew** [amyleew/osrm-frontend#8]
`leaflet-osrm-tools-josm`

**Comment by amyleew** [comment]
Downloaded [josm.openstreetmap.de](https://josm.openstreetmap.de/wiki/Download) locally and enabled `remote control` functionality for listening to localhost `8111` and `8112`. 

Getting the following error from clicking button on tool:

![image](https://cloud.githubusercontent.com/assets/4587826/8658190/49a11228-2970-11e5-9003-2936556b57c4.png)

**Comment by amyleew** [comment]
Try `OAuth` token vs. Basic Connection for better connection?

![image](https://cloud.githubusercontent.com/assets/4587826/8658358/3e4472e8-2971-11e5-8bb6-fffa21afb5aa.png)

/cc @lxbarth

**Comment by lxbarth** [comment]
Use OAuth.

**Comment by amyleew** [comment]
working @lxbarth thanks!

**Comment by amyleew** [comment]
Completed [c9ac4f4](https://github.com/amyleew/osrm-frontend/commit/db00b5826a72ed5f4340cd2bc4e439fdf1d06c6f)
